
all:
    cd tgrocery/learner  && $(MAKE) -f Makefile.win clean all && cd ../..

liball:
    cd tgrocery/learner  && $(MAKE) -f Makefile.win clean liball && cd ../..

clean:
    -erase /Q *.svm *.converter *.model *.config *.out *.pyc
	cd tgrocery/learner  && $(MAKE) -f Makefile.win clean && cd ../..